ELEMENTS = {
    'frame': '//*[@id="rsIFrameManager_1"]',
    'ELEMENTS_LOGIN': {
        'namespace_dropdown_button': 'downshift-0-toggle-button',
        'namespace_azuread': 'downshift-0-item-0',
        'email': 'i0116',
        'password': 'i0118',
        'submit_button': 'idSIButton9',
        'element_title': 'ibm',
        'element_banner': 'bannerLogo',
        'element_title_v2': 'bx--row',
    },
    'ELEMENTS_OLPN': {
        'element_filial_id': 'dv17_ValueComboBox',
        'element_filial': ['1200','1400'],
        'element_title': 'tt',
        'element_dt_start': 'dv59__tblDateTextBox__txtInput',
        'element_dt_end': 'dv67__tblDateTextBox__txtInput',
        'element_listbox': '//*[@id="dv75_MultiSelectList"]',
        'elements_listbox': '//tr[@role="option" and @checkboxitem="true"]',
        'element_get_item': 'aria-label',
        'element_get_checked': 'aria-checked',
        'element_confirm': 'dv135',
        'list_itens': [
            'S01 - ENTREGA A CLIENTES',
            'S02 - RETIRA CLIENTE DEPOSITO',
            'S03 - TRANSF.LOJA/ENTREGA CLIENTE',
            'S04 - TRANSF EAD AUTOMATICA',
            'S05 - TRANSF EAD PROGRAMADA',
            'S06- ENTREGA A CLIENTE REMANEJADA',
            'S07 - EAD AUTOMATICO REMANEJADA',
            'S08 - TRANSF.LOJA/ENTR. CLIENTE REM',
            'S09 - TRANSF. PROGRAMADA REMANEJADA',
            'S10 - REM.FORNECEDOR ASSIST.TECNICA',
            'S11 - TRANSF. LOJA VIA DEPOSITO BOA',
            'S12 - TRANSF.LOJA VIA DEPOSITO QEB',
            'S13 - ABASTECIMENTO DE LOJA BOA',
            'S14 - ABASTECIMENTO DE LOJA QEB',
            'S15 - OUTRAS SAIDAS BOA',
            'S16 - OUTRAS SAIDAS QEB',
            'S18 - REMESSA PARA CONSERTO',
            'S19 - DEVOLUÇÃO P/ FORNECEDOR A1',
            'S26 - EXPEDIÇÃO DE EAD AUTOMATICO',
            'S27 - REMESSA PARA DEPOSITO QEB',
            'S28 - REMANEJADO EAD AUTOMATICO',
            'S29 - ABM CROSS DOCK BOA',
            'S30 - ABM CROSS DOCK QEB',
            'S31 - EXP PED RET 31',
            'S32 - EAD VVLOG',
            'S33 - VENDA MIUDEZAS',
            'S34 - DEV EAD BOM',
            'S35 - DEV EAD RETIRA CLIENTE',
            'S39 - EXPEDICAO LEVES',
            'S39I - EXPEDICAO LEVES',
            'S39M - EXPEDICAO LEVES',
            'S39P - EXPEDICAO LEVES',
            'S39R - Single line',
            'S41 - INTERCOMPANY BOA',
            'S42 - INTERCOMPANY QEB',
            'S43 - ENTREGA BARATEIRO',
            'S44 - ENTREGA BARATEIRO LEVES',
            'S45 - EXPEDIÇÃO ENTREGA PELOEXTRA',
            'S46 - ABASTECIMENTO RETIRA LOJA',
            'S48 - ABASTECIMENTO CEL RJ',
            'S53 - TRANSFERENCIA ENTRE CDS',
            'S55 - EAD Faturado (Pesado)',
            'S56 - EAD Faturado (Leves)',
            'S56I - EAD Faturado (Leves)',
            'S56M - EAD Faturado (Leves)',
            'S56P - EAD Faturado (Leves)',
            'S56R - Transit point singleline',
            'S71 - SAIDAS QE FILIAL VIRTUAL 0014',
            'S99 - Intercompany'
        ]
    },
    'ELEMENTS_CANCEL': {
        'element_filial_id': 'dv20_ValueComboBox',
        'element_filial': '1200',
        'element_dt_start': 'dv62__tblDateTextBox__txtInput',
        'element_dt_end': 'dv71__tblDateTextBox__txtInput',
        'element_confirm': 'dv81'
    },
    'ELEMENTS_PICKING': {
        'element_filial_id': 'dv18_ValueComboBox',
        'element_filial': '1200',
        'element_dt_start': 'dv114__tblDateTextBox__txtInput',
        'element_dt_end': 'dv124__tblDateTextBox__txtInput',
        'element_listbox': '//*[@id="dv58_MultiSelectList"]',
        'elements_listbox': '//tr[@role="option" and @checkboxitem="true"]',
        'element_get_item': 'aria-label',
        'element_get_checked': 'aria-checked',
        'element_confirm': 'dv131',
        'list_itens': [
            'S01 - ENTREGA A CLIENTES',
            'S02 - RETIRA CLIENTE DEPOSITO',
            'S03 - TRANSF.LOJA/ENTREGA CLIENTE',
            'S04 - TRANSF EAD AUTOMATICA',
            'S05 - TRANSF EAD PROGRAMADA',
            'S06- ENTREGA A CLIENTE REMANEJADA',
            'S07 - EAD AUTOMATICO REMANEJADA',
            'S08 - TRANSF.LOJA/ENTR. CLIENTE REM',
            'S09 - TRANSF. PROGRAMADA REMANEJADA',
            'S10 - REM.FORNECEDOR ASSIST.TECNICA',
            'S11 - TRANSF. LOJA VIA DEPOSITO BOA',
            'S12 - TRANSF.LOJA VIA DEPOSITO QEB',
            'S13 - ABASTECIMENTO DE LOJA BOA',
            'S14 - ABASTECIMENTO DE LOJA QEB',
            'S15 - OUTRAS SAIDAS BOA',
            'S16 - OUTRAS SAIDAS QEB',
            'S18 - REMESSA PARA CONSERTO',
            'S19 - DEVOLUÇÃO P/ FORNECEDOR A1',
            'S26 - EXPEDIÇÃO DE EAD AUTOMATICO',
            'S27 - REMESSA PARA DEPOSITO QEB',
            'S28 - REMANEJADO EAD AUTOMATICO',
            'S29 - ABM CROSS DOCK BOA',
            'S30 - ABM CROSS DOCK QEB',
            'S31 - EXP PED RET 31',
            'S32 - EAD VVLOG',
            'S33 - VENDA MIUDEZAS',
            'S34 - DEV EAD BOM',
            'S35 - DEV EAD RETIRA CLIENTE',
            'S39 - EXPEDICAO LEVES',
            'S39I - EXPEDICAO LEVES',
            'S39M - EXPEDICAO LEVES',
            'S39P - EXPEDICAO LEVES',
            'S39R - Single line',
            'S41 - INTERCOMPANY BOA',
            'S42 - INTERCOMPANY QEB',
            'S43 - ENTREGA BARATEIRO',
            'S44 - ENTREGA BARATEIRO LEVES',
            'S45 - EXPEDIÇÃO ENTREGA PELOEXTRA',
            'S46 - ABASTECIMENTO RETIRA LOJA',
            'S48 - ABASTECIMENTO CEL RJ',
            'S53 - TRANSFERENCIA ENTRE CDS',
            'S55 - EAD Faturado (Pesado)',
            'S56 - EAD Faturado (Leves)',
            'S56I - EAD Faturado (Leves)',
            'S56M - EAD Faturado (Leves)',
            'S56P - EAD Faturado (Leves)',
            'S56R - Transit point single line',
            'S71 - SAIDAS QE FILIAL VIRTUAL 0014',
            'S99 - Intercompany'
        ]
    },
    'ELEMENTS_PUTAWAY': {
        'element_filial_id': 'dv9_ValueComboBox',
        'element_filial': '1200',
        'element_dt_start': 'dv51__tblDateTextBox__txtInput',
        'element_dt_end': 'dv59__tblDateTextBox__txtInput',
        'element_listbox': '//*[@id="dv67_MultiSelectList"]',
        'elements_listbox': '//tr[@role="option" and @checkboxitem="true"]',
        'element_get_item': 'aria-label',
        'element_get_checked': 'aria-checked',
        'element_confirm': 'dv126',
        'list_itens': [
            'S01 - ENTREGA A CLIENTES',
            'S02 - RETIRA CLIENTE DEPOSITO',
            'S03 - TRANSF.LOJA/ENTREGA CLIENTE',
            'S04 - TRANSF EAD AUTOMATICA',
            'S05 - TRANSF EAD PROGRAMADA',
            'S06- ENTREGA A CLIENTE REMANEJADA',
            'S07 - EAD AUTOMATICO REMANEJADA',
            'S08 - TRANSF.LOJA/ENTR. CLIENTE REM',
            'S09 - TRANSF. PROGRAMADA REMANEJADA',
            'S10 - REM.FORNECEDOR ASSIST.TECNICA',
            'S11 - TRANSF. LOJA VIA DEPOSITO BOA',
            'S12 - TRANSF.LOJA VIA DEPOSITO QEB',
            'S13 - ABASTECIMENTO DE LOJA BOA',
            'S14 - ABASTECIMENTO DE LOJA QEB',
            'S15 - OUTRAS SAIDAS BOA',
            'S16 - OUTRAS SAIDAS QEB',
            'S18 - REMESSA PARA CONSERTO',
            'S19 - DEVOLUÇÃO P/ FORNECEDOR A1',
            'S26 - EXPEDIÇÃO DE EAD AUTOMATICO',
            'S27 - REMESSA PARA DEPOSITO QEB',
            'S28 - REMANEJADO EAD AUTOMATICO',
            'S29 - ABM CROSS DOCK BOA',
            'S30 - ABM CROSS DOCK QEB',
            'S31 - EXP PED RET 31',
            'S32 - EAD VVLOG',
            'S33 - VENDA MIUDEZAS',
            'S34 - DEV EAD BOM',
            'S35 - DEV EAD RETIRA CLIENTE',
            'S39 - EXPEDICAO LEVES',
            'S39I - EXPEDICAO LEVES',
            'S39M - EXPEDICAO LEVES',
            'S39P - EXPEDICAO LEVES',
            'S39R - Single line',
            'S41 - INTERCOMPANY BOA',
            'S42 - INTERCOMPANY QEB',
            'S43 - ENTREGA BARATEIRO',
            'S44 - ENTREGA BARATEIRO LEVES',
            'S45 - EXPEDIÇÃO ENTREGA PELOEXTRA',
            'S46 - ABASTECIMENTO RETIRA LOJA',
            'S48 - ABASTECIMENTO CEL RJ',
            'S53 - TRANSFERENCIA ENTRE CDS',
            'S55 - EAD Faturado (Pesado)',
            'S56 - EAD Faturado (Leves)',
            'S56I - EAD Faturado (Leves)',
            'S56M - EAD Faturado (Leves)',
            'S56P - EAD Faturado (Leves)',
            'S56R - Transit point singleline',
            'S71 - SAIDAS QE FILIAL VIRTUAL 0014',
            'S99 - Intercompany'
        ]    
    },
    'ELEMENTS_PACKING': {
        'element_dt_start': '//*[@id="dv106_DateInput_Current"]',
        'calendario_start' : {
            'retornar': 'dv106__calYear_down'
        },
        'element_dt_end': '//*[@id="dv110_DateInput_Current"]',
        'calendario_end': {
            'retornar': 'dv110__calYear_down'
        },
        'id_dia_inicio': 'dv106__calDay_', # controlar ultimo caracter
        'id_dia_fim': 'dv110__calDay_', # controlar ultimo caracter
        'element_filial_id': 'dv13_ValueComboBox',
        'element_filial': '1200',
        'element_listbox': '//*[@id="dv51_MultiSelectList"]',
        'elements_listbox': '//tr[@role="option" and @checkboxitem="true"]',
        'element_get_item': 'aria-label',
        'element_get_checked': 'aria-checked',
        'element_confirm': 'dv116',
        'list_itens': [
            'S01 - ENTREGA A CLIENTES',
            'S02 - RETIRA CLIENTE DEPOSITO',
            'S03 - TRANSF.LOJA/ENTREGA CLIENTE',
            'S04 - TRANSF EAD AUTOMATICA',
            'S05 - TRANSF EAD PROGRAMADA',
            'S06- ENTREGA A CLIENTE REMANEJADA',
            'S07 - EAD AUTOMATICO REMANEJADA',
            'S08 - TRANSF.LOJA/ENTR. CLIENTE REM',
            'S09 - TRANSF. PROGRAMADA REMANEJADA',
            'S10 - REM.FORNECEDOR ASSIST.TECNICA',
            'S11 - TRANSF. LOJA VIA DEPOSITO BOA',
            'S12 - TRANSF.LOJA VIA DEPOSITO QEB',
            'S13 - ABASTECIMENTO DE LOJA BOA',
            'S14 - ABASTECIMENTO DE LOJA QEB',
            'S15 - OUTRAS SAIDAS BOA',
            'S16 - OUTRAS SAIDAS QEB',
            'S18 - REMESSA PARA CONSERTO',
            'S19 - DEVOLUÇÃO P/ FORNECEDOR A1',
            'S26 - EXPEDIÇÃO DE EAD AUTOMATICO',
            'S27 - REMESSA PARA DEPOSITO QEB',
            'S28 - REMANEJADO EAD AUTOMATICO',
            'S29 - ABM CROSS DOCK BOA',
            'S30 - ABM CROSS DOCK QEB',
            'S31 - EXP PED RET 31',
            'S32 - EAD VVLOG',
            'S33 - VENDA MIUDEZAS',
            'S34 - DEV EAD BOM',
            'S35 - DEV EAD RETIRA CLIENTE',
            'S39 - EXPEDICAO LEVES',
            'S39I - EXPEDICAO LEVES',
            'S39M - EXPEDICAO LEVES',
            'S39P - EXPEDICAO LEVES',
            'S39R - Single line',
            'S41 - INTERCOMPANY BOA',
            'S42 - INTERCOMPANY QEB',
            'S43 - ENTREGA BARATEIRO',
            'S44 - ENTREGA BARATEIRO LEVES',
            'S45 - EXPEDIÇÃO ENTREGA PELOEXTRA',
            'S46 - ABASTECIMENTO RETIRA LOJA',
            'S48 - ABASTECIMENTO CEL RJ',
            'S53 - TRANSFERENCIA ENTRE CDS',
            'S55 - EAD Faturado (Pesado)',
            'S56 - EAD Faturado (Leves)',
            'S56I - EAD Faturado (Leves)',
            'S56M - EAD Faturado (Leves)',
            'S56P - EAD Faturado (Leves)',
            'S56R - Transit point singleline',
            'S71 - SAIDAS QE FILIAL VIRTUAL 0014',
            'S99 - Intercompany'
        ]    
    },
    'ELEMENTS_LOADING': {
        'element_dt_start': '//*[@id="dv106_DateInput_Current"]',
        'calendario_start' : {
            'retornar': 'dv106__calYear_down'
        },
        'element_dt_end': '//*[@id="dv110_DateInput_Current"]',
        'calendario_end': {
            'retornar': 'dv110__calYear_down'
        },
        'id_dia_inicio': 'dv106__calDay_', # controlar ultimo caracter
        'id_dia_fim': 'dv110__calDay_', # controlar ultimo caracter
        'element_filial_id': 'dv13_ValueComboBox',
        'element_filial': '1200',
        'element_listbox': '//*[@id="dv51_MultiSelectList"]',
        'elements_listbox': '//tr[@role="option" and @checkboxitem="true"]',
        'element_get_item': 'aria-label',
        'element_get_checked': 'aria-checked',
        'element_confirm': 'dv116',
        'list_itens': [
            'S01 - ENTREGA A CLIENTES',
            'S02 - RETIRA CLIENTE DEPOSITO',
            'S03 - TRANSF.LOJA/ENTREGA CLIENTE',
            'S04 - TRANSF EAD AUTOMATICA',
            'S05 - TRANSF EAD PROGRAMADA',
            'S06- ENTREGA A CLIENTE REMANEJADA',
            'S07 - EAD AUTOMATICO REMANEJADA',
            'S08 - TRANSF.LOJA/ENTR. CLIENTE REM',
            'S09 - TRANSF. PROGRAMADA REMANEJADA',
            'S10 - REM.FORNECEDOR ASSIST.TECNICA',
            'S11 - TRANSF. LOJA VIA DEPOSITO BOA',
            'S12 - TRANSF.LOJA VIA DEPOSITO QEB',
            'S13 - ABASTECIMENTO DE LOJA BOA',
            'S14 - ABASTECIMENTO DE LOJA QEB',
            'S15 - OUTRAS SAIDAS BOA',
            'S16 - OUTRAS SAIDAS QEB',
            'S18 - REMESSA PARA CONSERTO',
            'S19 - DEVOLUÇÃO P/ FORNECEDOR A1',
            'S26 - EXPEDIÇÃO DE EAD AUTOMATICO',
            'S27 - REMESSA PARA DEPOSITO QEB',
            'S28 - REMANEJADO EAD AUTOMATICO',
            'S29 - ABM CROSS DOCK BOA',
            'S30 - ABM CROSS DOCK QEB',
            'S31 - EXP PED RET 31',
            'S32 - EAD VVLOG',
            'S33 - VENDA MIUDEZAS',
            'S34 - DEV EAD BOM',
            'S35 - DEV EAD RETIRA CLIENTE',
            'S39 - EXPEDICAO LEVES',
            'S39I - EXPEDICAO LEVES',
            'S39M - EXPEDICAO LEVES',
            'S39P - EXPEDICAO LEVES',
            'S39R - Single line',
            'S41 - INTERCOMPANY BOA',
            'S42 - INTERCOMPANY QEB',
            'S43 - ENTREGA BARATEIRO',
            'S44 - ENTREGA BARATEIRO LEVES',
            'S45 - EXPEDIÇÃO ENTREGA PELOEXTRA',
            'S46 - ABASTECIMENTO RETIRA LOJA',
            'S48 - ABASTECIMENTO CEL RJ',
            'S53 - TRANSFERENCIA ENTRE CDS',
            'S55 - EAD Faturado (Pesado)',
            'S56 - EAD Faturado (Leves)',
            'S56I - EAD Faturado (Leves)',
            'S56M - EAD Faturado (Leves)',
            'S56P - EAD Faturado (Leves)',
            'S56R - Transit point singleline',
            'S71 - SAIDAS QE FILIAL VIRTUAL 0014',
            'S99 - Intercompany'
        ]    
    }
}